
services:
  postgres_ms1:
    image: postgres:15
    container_name: postgres_ms1
    environment:
      POSTGRES_DB: ms1_db
      POSTGRES_USER: ms1_user
      POSTGRES_PASSWORD: ms1_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata_ms1:/var/lib/postgresql/data

  postgres_ms2:
    image: postgres:15
    container_name: postgres_ms2
    environment:
      POSTGRES_DB: ms2_db
      POSTGRES_USER: ms2_user
      POSTGRES_PASSWORD: ms2_pass
    ports:
      - "5434:5432"
    volumes:
      - pgdata_ms2:/var/lib/postgresql/data

  postgres_ms3:
    image: postgres:15
    container_name: postgres_ms3
    environment:
      POSTGRES_DB: ms3_db
      POSTGRES_USER: ms3_user
      POSTGRES_PASSWORD: ms3_pass
    ports:
      - "5435:5432"
    volumes:
      - pgdata_ms3:/var/lib/postgresql/data

  postgres_ms4:
    image: postgres:15
    container_name: postgres_ms4
    environment:
      POSTGRES_DB: ms4_db
      POSTGRES_USER: ms4_user
      POSTGRES_PASSWORD: ms4_pass
    ports:
      - "5436:5432"
    volumes:
      - pgdata_ms4:/var/lib/postgresql/data

  postgres_ms5:
    image: postgres:15
    container_name: postgres_ms5
    environment:
      POSTGRES_DB: ms5_db
      POSTGRES_USER: ms5_user
      POSTGRES_PASSWORD: ms5_pass
    ports:
      - "5437:5432"
    volumes:
      - pgdata_ms5:/var/lib/postgresql/data

  postgres_ms6:
    image: postgres:15
    container_name: postgres_ms6
    environment:
      POSTGRES_DB: ms6_db
      POSTGRES_USER: ms6_user
      POSTGRES_PASSWORD: ms6_pass
    ports:
      - "5438:5432"
    volumes:
      - pgdata_ms6:/var/lib/postgresql/data

volumes:
  pgdata_ms1:
  pgdata_ms2:
  pgdata_ms3:
  pgdata_ms4:
  pgdata_ms5:
  pgdata_ms6:
