export const countries = [
  { code: "FR", name: "France" },
  { code: "BE", name: "Belgique" },
  { code: "CH", name: "Suisse" },
  { code: "CA", name: "Canada" },
  { code: "MA", name: "Maroc" },
  { code: "SN", name: "Sénégal" },
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "TN", name: "Tunisie" },
  { code: "DZ", name: "Algérie" },
  { code: "CM", name: "Cameroun" },
  { code: "MG", name: "Madagascar" },
  { code: "ML", name: "Mali" },
  { code: "NE", name: "Niger" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BJ", name: "Bénin" },
  { code: "TG", name: "Togo" },
  { code: "GN", name: "Guinée" },
  { code: "CD", name: "République démocratique du Congo" },
  { code: "CG", name: "République du Congo" },
  { code: "GA", name: "Gabon" },
  { code: "BI", name: "Burundi" },
  { code: "RW", name: "Rwanda" },
  { code: "HT", name: "Haïti" },
  { code: "LB", name: "Liban" },
  { code: "VN", name: "Vietnam" },
  { code: "KH", name: "Cambodge" },
  { code: "LA", name: "Laos" },
  // Ajoutez d'autres pays selon vos besoins
]
