name: CI + Docker Build & Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service, inscription-service, education-service, pilotage-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build and test ${{ matrix.service }}
        working-directory: backend/${{ matrix.service }}
        run: ./mvnw clean verify

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image for ${{ matrix.service }}
        working-directory: backend/${{ matrix.service }}
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}
          docker build -t $IMAGE_NAME:latest .

      # - name: Push Docker image for ${{ matrix.service }}
      #   working-directory: backend/${{ matrix.service }}
      #   run: |
      #     IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}
      #     docker push $IMAGE_NAME:latest
